### ISSUE TITLE
Overhaul stats tracking

### ISSUE THREAD

**Issue by sorentwo** [oban-bg/oban_web#20]
The current implementation has a few problems that result in inaccurate numbers:

- [x] The queue limits are read from the config, which isn't very accurate
- [x] Dead node information is kept forever
- [x] Incorrect counts from state changes can result in negative numbers

I believe all of these things can be improved by basing stats primarily on `oban_beats` information. The stats server could really use some stateful property tests to prove it as well.
